### ISSUE TITLE
Several issues regarding boost-1.70 and python

### ISSUE THREAD

**Issue by waebbl** [LuxCoreRender/LuxCore#223]
The current way to find boost doesn't work anymore for boost-1.70.0. Boost again changed the way, of how some libraries are named. The python and numpy libraries are named like `libboost_{python,numpy}${PYTHON_MAJOR_VERSION}${PYTHON_MINOR_VERSION}` which is not mirrored with the current solution.

If this gets patched, another issue with `fpclassify.hpp` occur:
```
[38/687] /usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_NO_DEPRECATED -DCPP_API_EXPORTS -DEIGEN_MPL2_ONLY -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Igenerated/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eigen-3.3.4 -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/bcd-1.1/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/bcd-1.1/include/bcd/core -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/openvdb-3.1.0 -isystem /opt/cuda/include -isystem /usr/include/OpenEXR  -O2 -pipe -march=bdver2 -fstack-protector-strong -fstack-check -std=c++11 -Wall -Wno-long-long -pedantic -msse -msse2 -msse3 -mssse3 -fPIC -fopenmp -DNDEBUG -O3 -ftree-vectorize -funroll-loops -fvariable-expansion-in-unroller   -DOPENVDB_3_ABI_COMPATIBLE -DOPENVDB_STATICLIB -DOPENVDB_OPENEXR_STATICLIB -MD -MT src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o -MF src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o.d -o src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o -c /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/slg/engines/tilepathcpu/tilepathcpu.cpp
FAILED: src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_NO_DEPRECATED -DCPP_API_EXPORTS -DEIGEN_MPL2_ONLY -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Igenerated/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eigen-3.3.4 -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/bcd-1.1/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/bcd-1.1/include/bcd/core -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/openvdb-3.1.0 -isystem /opt/cuda/include -isystem /usr/include/OpenEXR  -O2 -pipe -march=bdver2 -fstack-protector-strong -fstack-check -std=c++11 -Wall -Wno-long-long -pedantic -msse -msse2 -msse3 -mssse3 -fPIC -fopenmp -DNDEBUG -O3 -ftree-vectorize -funroll-loops -fvariable-expansion-in-unroller   -DOPENVDB_3_ABI_COMPATIBLE -DOPENVDB_STATICLIB -DOPENVDB_OPENEXR_STATICLIB -MD -MT src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o -MF src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o.d -o src/slg/CMakeFiles/slg-core.dir/engines/tilepathcpu/tilepathcpu.cpp.o -c /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/slg/engines/tilepathcpu/tilepathcpu.cpp
In file included from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/utils/serializationutils.h:47,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/core/geometry/vector.h:29,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/core/geometry/point.h:24,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/slg/film/film.h:34,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/slg/samplers/tilepathsampler.h:24,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/slg/engines/tilepathcpu/tilepathcpu.cpp:21:
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:125:10: fatal error: boost/spirit/home/support/detail/math/fpclassify.hpp: No such file or directory
 #include <boost/spirit/home/support/detail/math/fpclassify.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This happens for `portable_oarchive.hpp` and if it get's patched for `portable_iarchive.hpp` too. The file `fpclassify.hpp` has been moved to `boost/math/special_functions` with boost-1.70.0. I tried solving this, by adding another preprocessor statement, which checks for boost version >= 1.70.0 on both files and include the proper files and then get another error:
```
[46/687] /usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_NO_DEPRECATED -DCPP_API_EXPORTS -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Igenerated/include -isystem /opt/cuda/include -isystem /usr/include/OpenEXR  -O2 -pipe -march=bdver2 -fstack-protector-strong -fstack-check -std=c++11 -Wall -Wno-long-long -pedantic -msse -msse2 -msse3 -mssse3 -fPIC -fopenmp -DNDEBUG -O3 -ftree-vectorize -funroll-loops -fvariable-expansion-in-unroller -MD -MT src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o -MF src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o.d -o src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o -c /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp
FAILED: src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_NO_DEPRECATED -DCPP_API_EXPORTS -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include -I/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Igenerated/include -isystem /opt/cuda/include -isystem /usr/include/OpenEXR  -O2 -pipe -march=bdver2 -fstack-protector-strong -fstack-check -std=c++11 -Wall -Wno-long-long -pedantic -msse -msse2 -msse3 -mssse3 -fPIC -fopenmp -DNDEBUG -O3 -ftree-vectorize -funroll-loops -fvariable-expansion-in-unroller -MD -MT src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o -MF src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o.d -o src/luxrays/CMakeFiles/luxrays.dir/core/color/color.cpp.o -c /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp
In file included from /usr/include/boost/detail/endian.hpp:9,
                 from /usr/include/boost/archive/impl/basic_binary_iarchive.ipp:25,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_iarchive.hpp:456,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/utils/serializationutils.h:48,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/core/color/color.h:26,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp:19:
/usr/include/boost/predef/detail/endian_compat.h:11:161: note: #pragma message: The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead
 #pragma message("The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead")
                                                                                                                                                                 ^
In file included from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/utils/serializationutils.h:47,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/core/color/color.h:26,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp:19:
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp: In instantiation of ‘typename boost::enable_if<boost::is_floating_point<T> >::type eos::portable_oarchive::save(const T&, eos::portable_oarchive::dummy<3>) [with T = float; typename boost::enable_if<boost::is_floating_point<T> >::type = void]’:
/usr/include/boost/archive/detail/oserializer.hpp:93:9:   required from ‘static void boost::archive::save_access::save_primitive(Archive&, const T&) [with Archive = eos::portable_oarchive; T = float]’
/usr/include/boost/archive/detail/oserializer.hpp:237:40:   required from ‘static void boost::archive::detail::save_non_pointer_type<Archive>::save_primitive::invoke(Archive&, const T&) [with T = float; Archive = eos::portable_oarchive]’
/usr/include/boost/archive/detail/oserializer.hpp:315:22:   required from ‘static void boost::archive::detail::save_non_pointer_type<Archive>::invoke(Archive&, const T&) [with T = float; Archive = eos::portable_oarchive]’
/usr/include/boost/archive/detail/oserializer.hpp:539:18:   required from ‘void boost::archive::save(Archive&, T&) [with Archive = eos::portable_oarchive; T = const float]’
/usr/include/boost/archive/detail/common_oarchive.hpp:71:22:   required from ‘void boost::archive::detail::common_oarchive<Archive>::save_override(T&) [with T = const float; Archive = eos::portable_oarchive]’
/usr/include/boost/archive/basic_binary_oarchive.hpp:80:7:   [ skipping 15 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/serialization/export.hpp:84:1:   required from ‘struct boost::archive::detail::ptr_serialization_support<eos::portable_oarchive, luxrays::RGBColor>’
/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from ‘struct boost::archive::detail::_ptr_serialization_support<eos::portable_oarchive, luxrays::RGBColor>’
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:429:1:   required by substitution of ‘template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<eos::portable_oarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, eos::portable_oarchive*, boost::archive::detail::adl_tag) [with Serializable = luxrays::RGBColor]’
/usr/include/boost/serialization/export.hpp:121:38:   required from ‘void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = luxrays::RGBColor; mpl_::false_ = mpl_::bool_<false>]’
/usr/include/boost/serialization/export.hpp:131:9:   required from ‘const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = luxrays::RGBColor]’
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp:27:1:   required from here
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:385:26: error: no type named ‘bits’ in ‘traits’ {aka ‘struct boost::math::detail::fp_traits_native<float>’}
    typename traits::bits bits;
                          ^~~~
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:385:26: error: no type named ‘bits’ in ‘traits’ {aka ‘struct boost::math::detail::fp_traits_native<float>’}
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:393:41: error: ‘exponent’ is not a member of ‘traits’ {aka ‘boost::math::detail::fp_traits_native<float>’}
    case FP_NAN: bits = traits::exponent | traits::mantissa; break;
                        ~~~~~~~~~~~~~~~~~^~~~~~~~
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:393:41: error: ‘mantissa’ is not a member of ‘traits’ {aka ‘boost::math::detail::fp_traits_native<float>’}
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:394:46: error: ‘exponent’ is not a member of ‘traits’ {aka ‘boost::math::detail::fp_traits_native<float>’}
    case FP_INFINITE: bits = traits::exponent | (t<0) * traits::sign; break;
                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:394:54: error: ‘sign’ is not a member of ‘traits’ {aka ‘boost::math::detail::fp_traits_native<float>’}
    case FP_INFINITE: bits = traits::exponent | (t<0) * traits::sign; break;
                                                ~~~~~~^~~~~~~~
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_oarchive.hpp:397:36: error: ‘get_bits’ is not a member of ‘traits’ {aka ‘boost::math::detail::fp_traits_native<float>’}
    case FP_NORMAL: traits::get_bits(t, bits); break;
                    ~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/utils/serializationutils.h:48,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/include/luxrays/core/color/color.h:26,
                 from /var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp:19:
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_iarchive.hpp: In instantiation of ‘typename boost::enable_if<boost::is_floating_point<T> >::type eos::portable_iarchive::load(T&, eos::portable_iarchive::dummy<3>) [with T = float; typename boost::enable_if<boost::is_floating_point<T> >::type = void]’:
/usr/include/boost/archive/detail/iserializer.hpp:108:9:   required from ‘static void boost::archive::load_access::load_primitive(Archive&, T&) [with Archive = eos::portable_iarchive; T = float]’
/usr/include/boost/archive/detail/iserializer.hpp:384:40:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::load_primitive::invoke(Archive&, T&) [with T = float; Archive = eos::portable_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:461:22:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::invoke(Archive&, T&) [with T = float; Archive = eos::portable_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:624:18:   required from ‘void boost::archive::load(Archive&, T&) [with Archive = eos::portable_iarchive; T = float]’
/usr/include/boost/archive/detail/common_iarchive.hpp:67:22:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&) [with T = float; Archive = eos::portable_iarchive]’
/usr/include/boost/archive/basic_binary_iarchive.hpp:75:7:   [ skipping 15 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/serialization/export.hpp:84:1:   required from ‘struct boost::archive::detail::ptr_serialization_support<eos::portable_iarchive, luxrays::RGBColor>’
/usr/include/boost/archive/detail/register_archive.hpp:25:8:   required from ‘struct boost::archive::detail::_ptr_serialization_support<eos::portable_iarchive, luxrays::RGBColor>’
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_iarchive.hpp:446:1:   required by substitution of ‘template<class Serializable> typename boost::archive::detail::_ptr_serialization_support<eos::portable_iarchive, Serializable>::type boost::archive::detail::instantiate_ptr_serialization(Serializable*, eos::portable_iarchive*, boost::archive::detail::adl_tag) [with Serializable = luxrays::RGBColor]’
/usr/include/boost/serialization/export.hpp:121:38:   required from ‘void boost::archive::detail::extra_detail::guid_initializer<T>::export_guid(mpl_::false_) const [with T = luxrays::RGBColor; mpl_::false_ = mpl_::bool_<false>]’
/usr/include/boost/serialization/export.hpp:131:9:   required from ‘const boost::archive::detail::extra_detail::guid_initializer<T>& boost::archive::detail::extra_detail::guid_initializer<T>::export_guid() const [with T = luxrays::RGBColor]’
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/src/luxrays/core/color/color.cpp:27:1:   required from here
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_iarchive.hpp:401:26: error: no type named ‘bits’ in ‘traits’ {aka ‘struct boost::math::detail::fp_traits_native<float>’}
    typename traits::bits bits;
                          ^~~~
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_iarchive.hpp:401:26: error: no type named ‘bits’ in ‘traits’ {aka ‘struct boost::math::detail::fp_traits_native<float>’}
/var/tmp/portage/media-gfx/luxcorerender-2.1/work/LuxCore-luxcorerender_v2.1/deps/eos_portable_archive-v5.1/eos/portable_iarchive.hpp:406:20: error: ‘set_bits’ is not a member of ‘traits’ {aka ‘boost::math::detail::fp_traits_native<float>’}
    traits::set_bits(t, bits);
    ~~~~~~~~~~~~~~~~^~~~~~~~~
```

The `#pragma message` warning appears on a lot of other files too. I don't know how boost actually works, so this is a point, where I get stuck.

With cmake-3.12 kitware has also changed the way to find python installations. The `PythonImpl` and `PythonLibraries` targets to `find_package` have been obsoleted by `Python{,2,3}`.

I can provide a PR or patches to the changes I mentioned above.

**Comment by Dade916** [comment]
As far as I know, latest sources work fine with Boost v1.72.
